Repository fusionjs/fusion-plugin-redux-action-emitter-enhancer, pull requests merged in 2018-11, with the labels that each got.

#130 Upgrade dependencies for flow 0.85.
  package.json
  src/__tests__/index.node.js
  src/index.js
  yarn.lock
Labels: bugfix, dependencies, greenkeeping

#125 Handle non object actions
  src/__tests__/app.node.js
  src/index.js
Labels: bugfix

#132 Release v2.0.1
  package.json
Labels: release

#133 Upgrade dependencies
  package.json
  yarn.lock
Labels: greenkeeping
